### ISSUE TITLE
[Gazebo] Update step1 and step2 in CircleCI tab in new repo page

### ISSUE THREAD

**Issue by RulaKhaled** [codecov/engineering-team#1037]
IF THERE IS A GLOBAL TOKEN ALREADY GENERATED FOR THE ORG:
 
  - Update clipboard in step 1 to show global token
  - Update step 1 copy revision "global token"  
  - Update step 2 input, see below
  
  
  ``` 
orbs: codecov: 
    codecov/codecov@4.0.0 
workflows: 
    upload-to-codecov: 
        jobs: 
          - checkout 
          - codecov/upload

  ```
  
  Figma link: https://www.figma.com/file/erYepsBky6H0SqNNIfIbSb/GH-761?type=design&node-id=1-238&mode=design&t=hGPgo4EiBCN4OfzV-0
