### ISSUE TITLE
Missing lines table not showing

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1129]
**Describe the bug**
In this example: https://github.com/getsentry/sentry/pull/64245/

User notices the missing lines, but the the intended  table that has the files with missing lines is not appearing. 

Could be related to configuration adjustments in yaml missing header:

- https://github.com/codecov/worker/blob/e966132c1dd17faecc3f764faaa9ad9dfb242089/services/notification/notifiers/mixins/message/sections.py#L53-L54
- https://github.com/codecov/worker/blob/e966132c1dd17faecc3f764faaa9ad9dfb242089/services/notification/notifiers/mixins/message/sections.py#L53-L54

Related behavior: https://github.com/codecov/engineering-team/issues/1041

**Expected behavior**
that the table shows that outlines files related to the missing lines

![pr_comment_missing_lines](https://github.com/codecov/engineering-team/assets/87861036/3f516d91-7a84-4ba0-a436-2d0957c1fc4e)

**Comment by eliatcodecov** [comment]
The action here is that the table should be part of the header so that it's displayed alongside the header. Assigning to @codecovdesign 

Likely more investigation to do here to determine if this is actually a bug or we just need to change the current settings and layout behavior.

**Comment by joseph-sentry** [comment]
Do we want to get rid of the old behaviour completely or leave it configurable?

**Comment by codecovdesign** [comment]
@joseph-sentry sorry, looks like I missed this, going to send you a quick sync to debug/discuss this one!

**Comment by codecovdesign** [comment]
review with @joseph-sentry, here is the config file that doesn't show the missing files

```
comment:
  # This is the addition of carry forward builds and fresh builds, thus, it's the addition
  # of the FE and BE builds
  after_n_builds: 22
  layout: 'diff, files'
  # Update, if comment exists. Otherwise post new.
  behavior: default
  # Comments will only post when coverage changes. Furthermore, if a comment
  # already exists, and a newer commit results in no coverage change for the
  # entire pull, the comment will be deleted.
  require_changes: true
  require_base: true # must have a base report to post
  require_head: true # must have a head report to post
  ```

the issue is the input of `files` doesn't include the `newfiles` ([source](https://github.com/codecov/worker/blob/50cd0a4f74d83bef0aadcd4255e1953cedab0682/services/notification/notifiers/mixins/message/sections.py#L4)) in this file we selected section names (https://github.com/codecov/worker/blob/50cd0a4f74d83bef0aadcd4255e1953cedab0682/services/notification/notifiers/mixins/message/__init__.py)

goal: we want the `newfile` table to show by default. update to show the missing files by default
