### ISSUE TITLE
Add stats emit cron integration with Brolly

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#117]
We need a cron task to emit statistics from the worker. These statistics will be consumed by a new "microservice", Brolly, that has been created to ingest this data.

Payload format
```json
{
"install_id": "UUID", # from the newly created install table in #118 
"users": "int", # the count of the users in the owners or users table
"repos": "int", # the count of repos in the repos table
"commits": "int", # the count of commits in the commits table
"uploads_24h": "int", # the count of uploads in the last 24 hours
"anonymous": "boolean", # optional default true. 
"version": "string", # the version of Codecov from the versions table
"admin_email": "string/email" # the email of the admin user (this is a new thing that we may defer)
}
```

This cron should run every 24 hours. 
It should be opt out via the codecov.yml.
The admin_email field can be added to codecov.yml.

Proposed yaml
```yaml
setup:
  telemetry:
    enabled: true # default true, when false don't run the cron job
    admin_email: null # default None, when set, send on payload
    anonymous: true # default True, This doesn't mean much at this time but good for future expansion
    url: null # default None, send to URL given by infra team by default
```
```[tasklist]
### Tasks
- [ ] Add yaml to yaml validator in shared
- [ ] Create cron task
```
