### ISSUE TITLE
Syntax error repo guide step 2

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#1171]
**Describe the bug**
In the repo guide page there is a slight syntax error, here is the current:
```
- name: Upload coverage reports to Codecov
  uses: codecov/codecov-action@v4.0.1
  env:
    token: ${{ secrets.CODECOV_TOKEN }}
    slug: Turing-Example/example_private
```
reported here: https://github.com/codecov/feedback/issues/18#issuecomment-1939325422

**Expected behavior**
the `env:` should be `with:`

However, it appears both are interchageable, but one or the other may not work in certain circumstances.

https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsenv
and
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepswith

Further investigation is needed to determine why both don't work interchangeably.
