### ISSUE TITLE
Make time interval configurable for resync

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#1308]
Make the [7 day threshold](https://github.com/codecov/worker/blob/main/tasks/sync_repo_languages.py#L20) be a configuration value that defaults to 7.

```yaml
setup:
  tasks:
    sync_repo_languages:
      sync_interval: int # default 7
```
