### ISSUE TITLE
Add ability to disable sync languages

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#1309]
Add check of config option to where this sync languages task [is queued](https://github.com/codecov/worker/blob/main/tasks/sync_repos.py#L111). If disabled, then do not queue it.

```yaml
setup:
  tasks:
    sync_repo_languages:
      enabled: BOOL # default true
```
