### ISSUE TITLE
Add ability to disable sync languages chaining from sync_repos manual invocation

### ISSUE THREAD

**Issue by trent-codecov** [codecov/engineering-team#1310]
On [sync repos](https://github.com/codecov/worker/blob/main/tasks/sync_repos.py#L111) make the check of manual trigger depend on configuration. Some environments, we will want to leave the sync on but not call the sync every time a manual run is triggered.

```yaml
setup:
  tasks:
    sync_repo_languages:
      manual_trigger_sync: BOOL # default true
```
