### ISSUE TITLE
Update YAML configuration

### ISSUE THREAD

**Issue by giovanni-guidini** [codecov/engineering-team#2004]
For the MVP the gating item is "entire bundle".

Example configuration
```YAML
bundle_analysis:
  status: True / False / "informational" # default is "informational"
  bundle_change_threshold: "10 mb" / "10%" / 100 # default is 10%

# This part already exists
comment:
  require_bundle_changes: True
  bundle_change_threshold: "10 mb" / "10%" / 100 # coercion needs to accept percentage
```

<details>
<summary> This is not part of the MVP </summary>
Ability to emit checks based on the different bundle groupings available

REPORT_SIZE (summary of all other cathegories)
JAVASCRIPT_SIZE
STYLESHEET_SIZE
FONT_SIZE
IMAGE_SIZE
ASSET_SIZE (all assets not classified in another cathegory)
</details>
