### ISSUE TITLE
[Shared] Add configuration option for list of repos to monitor

### ISSUE THREAD

**Issue by tnt-sentry** [codecov/engineering-team#2575]
Suggestion
```yaml
monitoring:
  repos:
    - id1
    - id2
    - id3
```

Above is the general idea. I'm open to other implementations.

Note that we already use the monitoring key for other things so its not a bad top level one to use if you don't nest it elsewhere.
