### ISSUE TITLE
Add logging to component filtering errors

### ISSUE THREAD

**Issue by drazisil-codecov** [codecov/engineering-team#2849]
While troubleshooting https://github.com/codecov/feedback/issues/557#issuecomment-2452406652

We traced the error to the message: `missing coverage for report with components`
There is ether something broken with `commit_components` or `filter_components_by_name` 

We might need to add a log statement or add to the `MissingCoverage` return object

**Comment by eliatcodecov** [comment]
assigned to @katia-sentry . There seems to be some prior context that this is an API level problem, but it's worth syncing with @nicholas-codecov to get more context. Please assign to either API or front end team member as needed.

**Comment by suejung-sentry** [comment]
It appears the issue reported by customer above is due to misconfiguration of the yaml. Codecov gazebo filters by `name` (not `id`) and their `codecov.yml` lacks any names.
Here is their yaml (public repo): https://github.com/Tellicious/ADV-utils/blob/29fd2388abfebe4617731f2c34207faaded0dfc4/codecov.yml#L29C5-L74C27
```
component_management:
    default_rules:
        statuses:
            - type: project
              target: auto
              branches:
                - '!main'
    individual_components:
        - component_id: basicMath
          paths:
            - "**/basicMath.*"
        - component_id: button
          paths:
            - "**/button.*"
          # see that `name` is missing here
...
```
See that `name` is missing within the `individual_components` listing.

Instead, it should look like something below.
```
    individual_components:
        - component_id: basicMath
          name: basicMath
          paths:
            - "**/basicMath.*"
        - component_id: button
          name: button
          paths:
            - "**/button.*"
    ...
```

For example, in gazebo: https://github.com/codecov/gazebo/blob/67b950ab91aa684d9812308947cd55a64f1dbd6f/codecov.yml#L61C1-L85C20

They can fix their yaml and make new commits and I believe that should resolve their issue.

I will also check with Product if we can filter by the id as well since the interaction can be confusing there.

Other note to self:
This appeared to happen in here too: https://github.com/codecov/internal-issues/issues/452#issuecomment-2209281464
