### ISSUE TITLE
Determine how after_n_builds should work when it's also configured for flags

### ISSUE THREAD

**Issue by rohan-at-sentry** [codecov/engineering-team#3214]
In the following scenario when should codecov run the notify task?

```
flags:
  frontend:
    after_n_builds: x
  backend:
    after_n_builds: y
comment:
  after_n_builds: z
```

How do we also handle cases such as https://github.com/getsentry/sentry/pull/83290#issuecomment-2584980112 where the PR comment didn't update because the front-end tests where skipped, because of which codecov got reports less than z
