### ISSUE TITLE
[TA] Deduplicate tests at cache file level in API

### ISSUE THREAD

**Issue by joseph-sentry** [codecov/engineering-team#3455]
Users are seeing duplicated test rows in the TA UI (likely because of uploads using flags), for now, we want to merge those into one row for each test (eventually we'd like to display more granular information about each test) 

for now we should just aggregate the cache file grouping by computed_name, merging each metric we're displaying (being careful to not do something like take the average of the average)

**Comment by taobojlen** [comment]
thanks! in case it's helpful, we're seeing this issue and this is how we upload results:

```yaml
      - name: Run tests
        run: poetry run coverage run --concurrency=multiprocessing manage.py test myapp --parallel --shuffle
      - run: poetry run coverage combine
      - run: poetry run coverage lcov
      - run: |
          echo '## Test Coverage Report' >> $GITHUB_STEP_SUMMARY
          poetry run coverage report --format markdown >> $GITHUB_STEP_SUMMARY
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./.django-test-results/
```
