### ISSUE TITLE
Update onboarding for global upload token usage (and CLI usage)

### ISSUE THREAD

**Issue by katia-sentry** [codecov/engineering-team#761]
## Problem to solve

- Shift onboarding instructions to emphasize the global upload token for CLI users, replacing repo-specific tokens.
     - org > setting (generate global token)
     -  repo guide page should indicate it's the global token and show ()
- Update onboarding to prioritize CLI over Node uploader.
     - the CLI must be used instead of the node uploader (step 2) 

## Solution

[view designs](https://www.figma.com/file/erYepsBky6H0SqNNIfIbSb/GH-761?type=design&node-id=1%3A238&mode=design&t=00mIdigyfwONNLms-1)

- update step 1 copy revision "global token"
     - If global token has been generated, otherwise show repo
- update step 2 input, see below

Additionally, see designs for updates related to CircleCI and Other tab

``` 
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v4
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

```[tasklist]
### Tasks
- [ ] https://github.com/codecov/engineering-team/issues/913
```
