### ISSUE TITLE
Add Label Support to AI PR Review

### ISSUE THREAD

**Issue by eliatcodecov** [codecov/engineering-team#896]
# Problem

Currently our ai pr review configuration is all or nothing. You get the reviews on every pr in the repo, or none of the PRs in the repo. This creates issues for larger teams / mono repos that may only want AI review occasionally. It also provides a large barrier to adopters if they'd rather selectively try this feature out on a few PRs before committing fully. 

# Solution

I propose that we add a new configuration setting to AI PR Review. Like so:

```yaml
ai_pr_review:
   enabled: true
   method: label
   label_name: "my label name"
```

This allows users to attach a label to the PRs where they are seeking an AI PR review. Additionally, the default configuration should be as such:

```yaml
ai_pr_review:
   enabled: true
   method: auto
```

This supports the current behavior of reviewing every PR for the repo. If `method: auto` is set and `label_name: "..."` is set, we simply ignore label_name. 

If label method is used, the AI Review will only happen when a label of "my label name" is attached to the PR. Other than this the AI review will work as it normally does. Providing an initial review and follow up reviews if new commits are pushed onto the PR.
