### ISSUE TITLE
Add AI PR Review YAML Schema to VS Code Extension

### ISSUE THREAD

**Issue by eliatcodecov** [codecov/engineering-team#906]
We need to add the AI Pr Review Schema to the yaml validator vs code extension. The current fields and their values are as follows:

```yaml
ai_pr_review:
  enabled: true                            # default false. Needed to enable the feature
  method: label                           # default auto. auto: all PRs will be reviews. label: only PRs labeled with `label_name` will be reviewed
  label_name: "ai-pr-review"    # name of the label on github that will trigger a review. Ignored if `method` is not `label`
```
