### ISSUE TITLE
Repo config instructions check image mismatch

### ISSUE THREAD

**Issue by codecovdesign** [codecov/engineering-team#907]

**Comment by MichaelHinrichs** [comment]
I'm the person who reported this problem. I've fiddled around with the yml file a bit.
```
jobs:
  coverage:
    name: codecov
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
```

Now i get this.
![CodecovChecks](https://github.com/codecov/engineering-team/assets/37460517/5e726075-4c9e-49da-8026-705548da281b)

One check for each OS makes sense, but now the checks for the pull request are gone, even though i didn't touch that part of the yml file at all.
```
on:
  push:
    branches:
      - main
      - CodecovBranch
  pull_request:
    branches:
      - main
      - CodecovBranch
```

And there's still no sign of "codecov/patch" or "codecov/project" with the pink logo. I still don't understand what the words to the right of the slash mean. I know they can't be branch names, because i named my branch to be clear that it is the branch, and not the workflow, job, or step, also named codecov. But in another repo that got it right, i don't see anything named "patch" or "project" anywhere in the workflow.
https://github.com/sanic-org/sanic/blob/main/.github/workflows/coverage.yml
