### ISSUE TITLE
[Gazebo] Update step1 and step2 in Github Actions tab in new repo page

### ISSUE THREAD

**Issue by RulaKhaled** [codecov/engineering-team#940]
- update hook to fetch orgUploadToken and update clipboard in step 1 to show global token
- update step 1 copy revision "global token"  
- update step 2 input, see below

``` 
- name: Upload coverage to Codecov
  uses: codecov/codecov-action@v4
  env:
    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

Figma link: https://www.figma.com/file/erYepsBky6H0SqNNIfIbSb/GH-761?type=design&node-id=1-238&mode=design&t=hGPgo4EiBCN4OfzV-0
